### ISSUE TITLE
vagrant.md - do not copy your keys!

### ISSUE THREAD

**Issue by L337hium** [ninrod/logbook#1]
https://github.com/ninrod/tricks/blob/master/vagrant.md

please do not copy your keys around! use the `ssh-agent` and vagrants build-in feature 'ssh.forward_agent = true' for this.

https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html

**Comment by ninrod** [comment]
Here's the problem I have. Every time that I restart my host, I have to issue a `ssh-add ~/.ssh/github_id_rsa` command. That command adds my key to `ssh-agent` right? I can't seem to make this change permanent. 
- On the other hand, if my key is named simply `id_rsa`, then I don't need to add the key to ssh-agent. 
- I think I'm screwing up something here. What you suggest specifically? I don't think I follow the `ssh-agent` part. I don't know how to properly configure it.

**Comment by L337hium** [comment]
I do not know if this is even possible with the sah-agent, In my bash profile config I just add all the keys right to the keyagent.
Like

```
find ${HOME}/.ssh -type f \
| while IFS= read -r FILE
do
  file "${FILE}" \
  | grep --silent --regexp='private key' \
  && ssh-add "${FILE}"
done
```

**Comment by ninrod** [comment]
Anyway, I don't think vagrant will stay relevant with the advent of `Docker for Mac` and `Docker for Windows`. You will be able to just create a mountpoint for you ~/.ssh directory and that's it.

**Comment by ninrod** [comment]
closing because vagrant will be irrelevant for docker purposes with the arrival of `docker for mac` and `dock for windows`.
